site_name: Monitoramento do Ar
theme: 
  name: null
  custom_dir: 'cinder'

pages:
  - Home: index.md

  - O Projeto:
    - Documento de Visão: 'Projeto/doc-visao.md'
    - Termo de Abertura do Projeto: 'Projeto/tap.md'
    - Plano de Comunicação: 'Projeto/comunicacao.md'
    - Plano de Metodologia: 'Projeto/metodologia.md'
    
  - Elétrica:
    - Proposta de Solução: 'Eletrica/solucao.md'
  
  - Estrutura: 
    - Proposta de Solução: 'Estrutura/solucao.md'

  - Software: 
    - Arquitetura: 'Software/arquitetura.md'
    - Mapeamento do Processo: 'Software/processo.md'
    - Principais Decisões do Projeto: 'Software/decisoes.md'
    - Proposta de Solução: 'Software/solucao.md'

