site_name: Monitoramento do Ar
theme: 
  name: null
  custom_dir: 'cinder'

nav:
  - Home: index.md

  - O Projeto:
    - Documento de Visão: 'Projeto/doc-visao.md'
    - Termo de Abertura do Projeto: 'Projeto/tap.md'
    - Plano de Gerenciamento de Comunicação: 'Projeto/comunicacao.md'

  - Elétrica:
    - Proposta de Solução: 'Eletrica/solucao.md'
  
  - Estrutura: 
    - About: 'Estrutura/estrutura.md'
    - Documentação: 'Estrutura/doc.md'

  - Software: 
    - Arquitetura: 'Software/arquitetura.md'
    - Mapeamento do Processo: 'Software/processo.md'
    - Principais Decisões do Projeto: 'Software/decisoes.md'
    - Proposta de Solução: 'Software/solucao.md'
    - Manual de Identidade Visual: 'Software/manual.md'


  - Other Pages: index.md
